name: Deploy to Firebase Hosting - cucuridu.web.app

on:
  push:
    branches:
      - main
    paths:
      - 'ignore/hosting/cucuridu.web.app/**'
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_KEY }}'
          channelId: live
          projectId: cucuridu21

          entryPoint: ./ignore/hosting/cucuridu.web.app/